# Generated by Django 6.0.6 on 2026-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название турнира')),
                ('game', models.CharField(choices=[('CS2', 'CS2'), ('VALORANT', 'VALORANT'), ('Dota 2', 'Dota 2'), ('Apex Legends', 'Apex Legends'), ('PUBG', 'PUBG'), ('Fortnite', 'Fortnite')], max_length=40, verbose_name='Игра')),
                ('format', models.CharField(choices=[('1x1', '1x1'), ('5x5', '5x5'), ('Solo', 'Solo'), ('Duo', 'Duo'), ('2x2', '2x2')], max_length=20, verbose_name='Формат')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('prize', models.PositiveIntegerField(verbose_name='Призовой фонд')),
                ('slots', models.PositiveIntegerField(verbose_name='Заполнено мест')),
                ('max_slots', models.PositiveIntegerField(verbose_name='Всего мест')),
                ('is_online', models.BooleanField(default=True, verbose_name='Онлайн')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Главный турнир')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ('date',),
            },
        ),
    ]
