# Generated by Django 6.0.6 on 2026-06-16 22:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название услуги')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('category', models.CharField(choices=[('periphery', 'Периферия'), ('food', 'Кухня и бар'), ('premium', 'Премиум'), ('tournaments', 'Турниры')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('period', models.CharField(blank=True, max_length=50, verbose_name='Период')),
                ('icon', models.CharField(default='fa-star', max_length=50, verbose_name='Иконка')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать как рекомендуемую')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('order', 'name'),
            },
        ),
    ]
