# Generated by Django 6.0.6 on 2026-06-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CyberX', max_length=120, verbose_name='Название клуба')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Слоган')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('profile_games', models.PositiveIntegerField(default=0, verbose_name='Всего игр')),
                ('profile_hours', models.FloatField(default=0.0, verbose_name='Всего часов')),
                ('profile_tournaments', models.PositiveIntegerField(default=0, verbose_name='Турниров')),
            ],
            options={
                'verbose_name': 'Информация о клубе',
                'verbose_name_plural': 'Информация о клубе',
            },
        ),
    ]
